"""Generate .github/workflows/evolve-<agent>.yml + drift detection.

P0 supports only the GitHub Actions backend. cron / launchd are P1.
"""

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from evolution.sdk import registry

log = logging.getLogger("evolution.sdk.scaffold")


class InvalidScheduleError(ValueError):
    """Raised when a schedule= value cannot be converted to a cron expression."""


# Spec §7.4 schedule syntax.
def schedule_to_cron(schedule: Optional[str]) -> Optional[str]:
    """Translate a schedule= declaration to a 5-field cron expression (or None).

    Returns None for schedule=None and schedule="on_min_samples".
    """
    if schedule is None:
        return None
    if schedule == "on_min_samples":
        return None
    if schedule == "weekly":
        return "57 8 * * 1"
    if schedule == "daily":
        return "57 8 * * *"
    if schedule == "hourly":
        return "57 * * * *"
    if schedule.startswith("cron:"):
        return schedule[len("cron:"):].strip()
    raise InvalidScheduleError(f"unknown schedule: {schedule!r}")


_HEADER = (
    "# Auto-generated by `evolution scaffold` — do not edit manually.\n"
    "# Regenerate: evolution scaffold --backend gh-actions --agent {name}\n"
    "# Source: @evolvable_agent(name=\"{name}\", schedule=\"{schedule}\", ...)\n"
)


def generate_gh_actions_yaml(reg: registry.AgentRegistration) -> str:
    """Render the workflow YAML for one agent."""
    cron = schedule_to_cron(reg.schedule)
    if cron is None:
        raise InvalidScheduleError(
            f"agent {reg.name!r} has no schedule (or on_min_samples); "
            "skip scaffold or use --backend none"
        )

    permissions = "  contents: read"
    if reg.apply == "pr":
        permissions += "\n  pull-requests: write"

    header = _HEADER.format(name=reg.name, schedule=reg.schedule)
    return f"""{header}
name: evolve-{reg.name}

on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false

permissions:
{permissions}

jobs:
  optimize:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      EVOLUTION_DEPLOY_MODE: production
      OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - run: pip install -e ".[dev]"
      - name: Optimize {reg.name}
        run: |
          python -m evolution.sdk.optimizer --agent {reg.name} ${{{{ inputs.dry_run && '--dry-run' || '' }}}}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: evolve-{reg.name}-${{{{ github.run_id }}}}
          path: output/sdk/{reg.name}/
          retention-days: 90
"""


@dataclass
class DriftStatus:
    agent: str
    file: Path
    status: str  # CLEAN | MISSING | DRIFT | MANUAL_EDIT | STALE
    detail: str = ""


def scaffold_gh_actions(*, output_dir: Path,
                        only_agent: Optional[str] = None) -> list[Path]:
    """Generate workflow files for all registered agents (or one).

    Returns list of files written. Agents with schedule_managed_by set are
    skipped (hermes adapter manages its own).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []
    manifest = {"version": 1, "agents": {}}
    manifest_path = output_dir / "evolution_scaffold_manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
        except json.JSONDecodeError:
            manifest = {"version": 1, "agents": {}}
            log.warning("manifest corrupt; rebuilding from scratch")

    targets = [registry.get_agent(only_agent)] if only_agent else [
        registry.get_agent(n) for n in registry.list_agents()
    ]
    targets = [r for r in targets if r is not None]

    for reg in targets:
        if reg.schedule_managed_by:
            log.info("skipping %s — schedule_managed_by=%s",
                     reg.name, reg.schedule_managed_by)
            continue
        if reg.schedule is None or reg.schedule == "on_min_samples":
            log.info("skipping %s — schedule=%s", reg.name, reg.schedule)
            continue

        path = output_dir / f"evolve-{reg.name}.yml"
        yaml_text = generate_gh_actions_yaml(reg)
        path.write_text(yaml_text)
        written.append(path)
        manifest["agents"][reg.name] = {
            "file": path.name,
            "hash": "sha256:" + hashlib.sha256(yaml_text.encode()).hexdigest(),
            "schedule": reg.schedule,
        }

    manifest_path.write_text(json.dumps(manifest, indent=2))
    return written


def check_drift(*, output_dir: Path) -> list[DriftStatus]:
    """Compare registry against on-disk workflow files.

    Returns one DriftStatus per agent. STALE agents (file exists but registry
    has schedule=None) are surfaced too.
    """
    statuses: list[DriftStatus] = []
    manifest_path = output_dir / "evolution_scaffold_manifest.json"
    manifest = {"agents": {}}
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
        except json.JSONDecodeError:
            log.warning("manifest unreadable; treating all as DRIFT")

    for name in registry.list_agents():
        reg = registry.get_agent(name)
        if reg.schedule_managed_by:
            continue
        expected_file = output_dir / f"evolve-{name}.yml"
        if reg.schedule in (None, "on_min_samples"):
            if expected_file.exists():
                statuses.append(DriftStatus(
                    agent=name, file=expected_file, status="STALE",
                    detail="schedule=None but file present",
                ))
            continue

        if not expected_file.exists():
            statuses.append(DriftStatus(
                agent=name, file=expected_file, status="MISSING",
                detail="schedule declared but file absent",
            ))
            continue

        actual = expected_file.read_text()
        actual_hash = "sha256:" + hashlib.sha256(actual.encode()).hexdigest()
        manifest_hash = manifest.get("agents", {}).get(name, {}).get("hash")

        # Always compare to "what we'd generate now" to catch registry drift.
        expected_now = generate_gh_actions_yaml(reg)
        expected_now_hash = "sha256:" + hashlib.sha256(expected_now.encode()).hexdigest()
        if actual_hash == expected_now_hash:
            statuses.append(DriftStatus(
                agent=name, file=expected_file, status="CLEAN",
                detail="manifest stale but file matches registry",
            ))
        elif _cron_value(actual) != _cron_value(expected_now):
            statuses.append(DriftStatus(
                agent=name, file=expected_file, status="DRIFT",
                detail="schedule mismatch — re-run scaffold",
            ))
        else:
            statuses.append(DriftStatus(
                agent=name, file=expected_file, status="MANUAL_EDIT",
                detail="content differs from generated; preserved",
            ))

    return statuses


def _cron_value(yaml_text: str) -> str:
    for line in yaml_text.splitlines():
        if "cron:" in line and '"' in line:
            return line.strip()
    return ""
