"""Phase 22 V2-LOOP-01 — gh CLI subprocess wrapper for PR creation.

Called by evolution.loop.run_loop after a successful evolve_* CLI run.
Creates a branch in the hermes-agent repo, copies the evolved artifact
into a staging subdir, pushes, and opens a PR via `gh pr create`.

Per D-03: PR target is hermes-agent (NOT evolution-self).
Per D-04: gh CLI subprocess only (NO PyGithub, NO requests).
Per D-05: branch naming = evolution/auto-loop/<loop_ts>/<artifact-kind>
Per D-09: branch protection + CODEOWNERS in hermes-agent enforce human review.

All subprocess calls use check=False; this module NEVER raises (except for
internal assertions which are caught and re-packaged). Errors return a
status dict so the caller (run_loop) can append to run_summary.json.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from evolution.core.external_importers import _contains_secret

# ── Constants ───────────────────────────────────────────────────────────

CLI_TO_ARTIFACT_KIND: dict[str, str] = {
    "skill":             "skill",
    "tool_descriptions": "tool-descriptions",
    "tool_params":       "tool-params",
    "tool_reasoning":    "tool-reasoning",
    "prompt_sections":   "prompt-sections",
    "code":              "code",
}

STAGING_BASE = "evolution-loop"
BOT_EMAIL = "evolution-bot@noreply.local"
BOT_NAME = "Phase 22 Evolution Loop"
PR_LABELS = ("auto-loop", "requires-human-review")

NOTICE_FALLBACK_TEMPLATE = """# NOTICE — LLM-generated artifact

This {artifact_kind} was generated by Phase 22 continuous evolution loop.

- CLI: evolve_{cli_name}
- Loop timestamp: {loop_ts}
- Output dir: {output_dir}
- Status: UNREVIEWED — DO NOT MERGE WITHOUT HUMAN REVIEW

## Metrics
{metrics_block}

Per Phase 22 D-09 / project policy (PROJECT.md), human review is required
before merge. The CODEOWNERS file in this repo + branch protection rules
enforce this gate. Auto-merge is explicitly out of scope.
"""


# ── Helpers ─────────────────────────────────────────────────────────────


def _redact(text: str) -> str:
    """Return text unchanged unless _contains_secret matches → [REDACTED]."""
    if text and _contains_secret(text):
        return "[REDACTED]"
    return text


def _run(cmd: list[str], cwd: Optional[Path] = None) -> subprocess.CompletedProcess:
    """Run a subprocess command with check=False, capture_output, text=True."""
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        check=False,
        timeout=300,
    )


def _discover_repo_slug(hermes_repo: Path) -> Optional[str]:
    """Return 'owner/repo' for the hermes-agent remote, or None on failure."""
    gh = _run(
        ["gh", "repo", "view", "--json", "owner,name", "-q",
         ".owner.login + \"/\" + .name"],
        cwd=hermes_repo,
    )
    if gh.returncode == 0 and gh.stdout.strip():
        slug = gh.stdout.strip()
        if "/" in slug and not _contains_secret(slug):
            return slug
    gr = _run(["git", "config", "--get", "remote.origin.url"], cwd=hermes_repo)
    if gr.returncode != 0:
        return None
    url = gr.stdout.strip()
    # git@github.com:owner/repo.git OR https://github.com/owner/repo(.git)
    m = re.search(r"[:/]([^/:]+/[^/:]+?)(?:\.git)?$", url)
    if m:
        slug = m.group(1)
        if "/" in slug and not _contains_secret(slug):
            return slug
    return None


def _build_branch(loop_ts: str, artifact_kind: str) -> str:
    # D-05 — both components must be safe (no secrets, no shell metachars).
    # Timestamp: strip to digits + underscore. Kind: validate against known
    # CLI_TO_ARTIFACT_KIND values; unknown kinds collapse to "unknown" so a
    # mangled or injected artifact_kind can't leak meaningful tokens into
    # the branch name (e.g. "tool;rm -rf /" → "unknown").
    safe_ts = re.sub(r"[^0-9_]", "", loop_ts)
    valid_kinds = set(CLI_TO_ARTIFACT_KIND.values())
    safe_kind = artifact_kind if artifact_kind in valid_kinds else "unknown"
    return f"evolution/auto-loop/{safe_ts}/{safe_kind}"


def _build_title(artifact_kind: str, loop_ts: str) -> str:
    return _redact(f"auto-loop: {artifact_kind} evolved at {loop_ts}")


def _build_body(
    cli_name: str,
    artifact_kind: str,
    loop_ts: str,
    output_dir: Path,
) -> str:
    notice = output_dir / "NOTICE.md"
    if notice.exists():
        body = notice.read_text(encoding="utf-8")
    else:
        metrics_block = "(no metrics.json)"
        metrics_path = output_dir / "metrics.json"
        if metrics_path.exists():
            try:
                data = json.loads(metrics_path.read_text())
                safe_data = {
                    k: ("[REDACTED]" if _contains_secret(str(v)) else v)
                    for k, v in data.items()
                }
                metrics_block = (
                    "```json\n"
                    + json.dumps(safe_data, indent=2, default=str)
                    + "\n```"
                )
            except Exception as e:
                metrics_block = f"(metrics.json unparseable: {type(e).__name__})"
        body = NOTICE_FALLBACK_TEMPLATE.format(
            artifact_kind=artifact_kind,
            cli_name=cli_name,
            loop_ts=loop_ts,
            output_dir=str(output_dir),
            metrics_block=metrics_block,
        )
    # Per-field redaction is already applied to metrics values above; we do
    # NOT wholesale-redact the assembled body because legitimate fixture and
    # CI paths can trip the Shannon-entropy heuristic in _contains_secret on
    # long base64-like path segments (false positives). Defense-in-depth
    # remains at the field-ingest layer (metrics values, slug, branch).
    return body


def _copy_artifacts_into_staging(
    output_dir: Path,
    hermes_repo: Path,
    artifact_kind: str,
    loop_ts: str,
) -> Path:
    """Copy all files from output_dir into hermes_repo/STAGING_BASE/<kind>/<ts>/.

    Returns the staging dir path.
    """
    dest = hermes_repo / STAGING_BASE / artifact_kind / loop_ts
    dest.mkdir(parents=True, exist_ok=True)
    for child in output_dir.iterdir():
        if child.is_file():
            shutil.copy2(child, dest / child.name)
        elif child.is_dir():
            shutil.copytree(child, dest / child.name, dirs_exist_ok=True)
    return dest


# ── Public API ──────────────────────────────────────────────────────────


def create_pr(
    *,
    cli_name: str,
    output_dir: Path,
    loop_ts: str,
    hermes_repo: Path,
) -> dict:
    """Create a PR in hermes-agent for the evolved artifact in output_dir.

    Returns a dict with keys: status, pr_url, reason, branch.
    See module docstring + Plan 04 PLAN.md <interfaces> for the contract.
    """
    artifact_kind = CLI_TO_ARTIFACT_KIND.get(cli_name, cli_name)
    branch = _build_branch(loop_ts, artifact_kind)
    result: dict = {
        "status": "error",
        "pr_url": None,
        "reason": None,
        "branch": branch,
    }

    if shutil.which("gh") is None:
        result["status"] = "skipped_no_gh"
        result["reason"] = "gh CLI not found in $PATH"
        return result

    if not hermes_repo.exists():
        result["reason"] = f"hermes_repo does not exist: {hermes_repo}"
        return result

    # 1. Verify hermes_repo is a clean git tree
    st = _run(["git", "status", "--porcelain"], cwd=hermes_repo)
    if st.returncode != 0:
        result["reason"] = (
            f"git status failed in hermes_repo: {_redact(st.stderr[-500:])}"
        )
        return result
    if st.stdout.strip():
        result["reason"] = (
            "hermes-agent has uncommitted changes; aborting (would taint PR diff)"
        )
        return result

    # 2. Discover repo slug
    slug = _discover_repo_slug(hermes_repo)
    if not slug:
        result["reason"] = (
            "could not determine owner/repo for hermes_repo "
            "(gh + git fallback both failed)"
        )
        return result

    # 3. Create branch (force-reset to current HEAD)
    co = _run(["git", "checkout", "-B", branch], cwd=hermes_repo)
    if co.returncode != 0:
        result["reason"] = (
            f"git checkout -B {branch} failed: {_redact(co.stderr[-500:])}"
        )
        return result

    # 4. Copy artifacts into staging
    try:
        _copy_artifacts_into_staging(output_dir, hermes_repo, artifact_kind, loop_ts)
    except Exception as e:
        result["reason"] = f"artifact copy failed: {type(e).__name__}: {e}"
        return result

    # 5. git add + commit (skip if no changes)
    ad = _run(["git", "add", "-A"], cwd=hermes_repo)
    if ad.returncode != 0:
        result["reason"] = f"git add failed: {_redact(ad.stderr[-500:])}"
        return result
    diff = _run(["git", "diff", "--cached", "--quiet"], cwd=hermes_repo)
    # exit 0 = no diff (nothing staged), exit 1 = diff exists
    if diff.returncode == 0:
        result["status"] = "skipped_no_changes"
        result["reason"] = "no staged changes after copy (artifact already present?)"
        return result

    commit_msg = (
        f"auto-loop: {artifact_kind} evolved at {loop_ts}\n\n"
        f"Source CLI: evolve_{cli_name}\n"
        f"Loop timestamp: {loop_ts}\n"
        f"Status: UNREVIEWED — DO NOT MERGE WITHOUT HUMAN REVIEW"
    )
    commit_msg = _redact(commit_msg) if _contains_secret(commit_msg) else commit_msg
    cm = _run(
        ["git", "-c", f"user.email={BOT_EMAIL}", "-c", f"user.name={BOT_NAME}",
         "commit", "-m", commit_msg],
        cwd=hermes_repo,
    )
    if cm.returncode != 0:
        result["reason"] = f"git commit failed: {_redact(cm.stderr[-500:])}"
        return result

    # 6. git push
    ps = _run(["git", "push", "-u", "origin", branch], cwd=hermes_repo)
    if ps.returncode != 0:
        result["reason"] = f"git push failed: {_redact(ps.stderr[-500:])}"
        return result

    # 7. gh pr create
    title = _build_title(artifact_kind, loop_ts)
    body = _build_body(cli_name, artifact_kind, loop_ts, output_dir)
    with tempfile.NamedTemporaryFile(
        "w", suffix=".md", delete=False, encoding="utf-8"
    ) as bf:
        bf.write(body)
        body_path = bf.name
    try:
        pr_cmd = [
            "gh", "pr", "create",
            "--repo", slug,
            "--head", branch,
            "--base", "main",
            "--title", title,
            "--body-file", body_path,
        ]
        for lbl in PR_LABELS:
            pr_cmd.extend(["--label", lbl])
        pr = _run(pr_cmd, cwd=hermes_repo)
    finally:
        try:
            os.unlink(body_path)
        except OSError:
            pass

    if pr.returncode != 0:
        result["reason"] = f"gh pr create failed: {_redact(pr.stderr[-500:])}"
        return result

    # 8. Parse PR URL from gh stdout (gh prints URL on success)
    url_match = re.search(r"https?://[^\s]+", pr.stdout or "")
    if url_match:
        result["pr_url"] = url_match.group(0)
        result["status"] = "created"
        result["reason"] = None
    else:
        # gh succeeded but no URL parsed — flag as ambiguous success
        result["status"] = "created"
        result["pr_url"] = None
        result["reason"] = "gh pr create exit 0 but no URL parsed from stdout"

    return result
