"""Single-import-surface facade for openevolve (D-03 architecture constraint).

This module is the ONLY file in the repository allowed to import openevolve.
The CI lint gate (.pre-commit-config.yaml `openevolve-single-import-surface` hook
+ tests/code/test_import_boundary.py) mechanically enforces this invariant.

Public API:
    evolve(target, config, output_dir, iterations, sandbox_timeout=120)
        -> EvolutionAdapterResult

The adapter is responsible for:
    1. ImportError guard with friendly install hint (D-03)
    2. EVOLVE-BLOCK marker injection around the target function body (Pitfall 5)
    3. Self-contained evaluator .py file generation (Pitfall 1)
    4. Bridge from EvolutionConfig to openevolve LLMModelConfig (D-04)
    5. openevolve Config assembly with PoC-conservative parameters (Pitfall 4)

NOT responsible for:
    - sandbox isolation (delegated to evolution.code.sandbox_runner — Plan 21-05)
    - fitness scoring (delegated to evolution.code.code_fitness — Plan 21-04)
    - CodeTarget discovery (delegated to evolution.code.code_target_loader — Plan 21-03)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional

try:
    from openevolve import Config, run_evolution
    from openevolve.config import LLMModelConfig
except ImportError as e:
    raise ImportError(
        "openevolve not installed. Run: pip install .[code]\n"
        f"Original error: {e}"
    ) from e

if TYPE_CHECKING:
    from evolution.code.code_target_loader import CodeTarget
    from evolution.core.config import EvolutionConfig


# ── PoC-conservative openevolve parameters (Pitfall 4) ─────────────────────
_OE_POPULATION_SIZE: int = 50
_OE_ARCHIVE_SIZE: int = 20
_OE_NUM_ISLANDS: int = 3
_OE_PARALLEL_EVALUATIONS: int = 1

DEFAULT_SANDBOX_TIMEOUT: int = 120

# ── EVOLVE-BLOCK markers (Pitfall 5) ───────────────────────────────────────
_EVOLVE_BLOCK_START_MARKER: str = "# EVOLVE-BLOCK-START"
_EVOLVE_BLOCK_END_MARKER: str = "# EVOLVE-BLOCK-END"

# Match `def strip_ansi(` at the start of a line (PoC target function name).
_DEF_LINE_RE = re.compile(r"^def\s+strip_ansi\s*\(", re.MULTILINE)


# ── Self-contained evaluator template (Pitfall 1) ──────────────────────────
# Variables substituted via str.format: {project_root}, {eval_dir_base},
# {baseline_size}, {test_file_path}, {train_test_ids}.
# Literal braces in the generated source are doubled ({{ / }}).
_EVALUATOR_TEMPLATE: str = '''"""Auto-generated openevolve evaluator (Plan 21-06).

This file is generated by evolution.code.code_evolver_adapter._generate_evaluator_file
for each evolve() invocation. It is self-contained (Pitfall 1): all evaluator state
lives in module-level constants below, NOT in closure variables from the parent
process. openevolve subprocess-spawns this file and imports `evaluate`.

DO NOT edit by hand — overwritten on every evolve() call.
"""

import sys
from pathlib import Path

sys.path.insert(0, "{project_root}")

EVAL_DIR_BASE = Path("{eval_dir_base}")
BASELINE_SIZE = {baseline_size}
TEST_FILE_PATH = Path("{test_file_path}")
TRAIN_TEST_IDS = {train_test_ids!r}


def evaluate(program_path: str) -> dict:
    """openevolve evaluator entry-point.

    Called by openevolve once per candidate. Delegates to score_candidate()
    in the parent project tree; the score_candidate function in turn calls
    sandbox_runner.run_pytest_in_sandbox() with restricted env + timeout +
    eval_dir cleanup (T-21-SECRET / T-21-DOS / T-21-LEAK).

    Returns a dict consumed by openevolve as the fitness signal. The
    `combined_score` key is the primary scalar; remaining keys are the
    D-16 reflection context for the next mutation prompt.
    """
    from evolution.code.code_fitness import score_candidate

    target_path = Path("{test_file_path}").parent.parent / "ansi_strip.py"

    fitness = score_candidate(
        target_path=target_path,
        evolved_path=Path(program_path),
        eval_dir=EVAL_DIR_BASE,
        baseline_size=BASELINE_SIZE,
        train_test_ids=TRAIN_TEST_IDS,
        test_file_path=TEST_FILE_PATH,
    )
    return {{
        "combined_score": fitness.composite,
        "pytest_passed": fitness.pytest_passed,
        "pytest_total": fitness.pytest_total,
        "size_component": fitness.size_component,
        "ruff_score": fitness.ruff_score,
        "pytest_failures": fitness.pytest_failures,
        "ruff_violations": fitness.ruff_findings,
        "decision": fitness.decision,
        "reject_reason": fitness.reject_reason,
    }}
'''


@dataclass(frozen=True)
class EvolutionAdapterResult:
    """Narrow result type — does NOT leak openevolve internal types.

    `optimizer_used` is always "openevolve" in this adapter; the field exists
    for symmetry with evolution.tools/prompts adapters that fall back across
    optimizers. Mutation-free dataclass (`frozen=True`) so the result is
    safe to share across the evolve_code orchestrator boundary.
    """

    best_code: str
    best_score: float
    iterations_run: int
    output_dir: Path
    optimizer_used: str = "openevolve"
    metrics: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "best_score": self.best_score,
            "iterations_run": self.iterations_run,
            "output_dir": str(self.output_dir),
            "optimizer_used": self.optimizer_used,
            "metrics": self.metrics,
        }


# ── Internal helpers ────────────────────────────────────────────────────────


def _inject_evolve_blocks(source: str) -> str:
    """Insert EVOLVE-BLOCK-START before `def strip_ansi(` and append END at EOF.

    Pitfall 5 mitigation — only the function body is mutable; imports and
    module constants stay outside the block. If both markers already exist
    the source is returned unchanged (idempotent).

    Raises:
        ValueError: when `def strip_ansi(` cannot be located.
    """
    if _EVOLVE_BLOCK_START_MARKER in source and _EVOLVE_BLOCK_END_MARKER in source:
        return source

    match = _DEF_LINE_RE.search(source)
    if match is None:
        raise ValueError(
            "Could not locate `def strip_ansi(` in target source — "
            "Pitfall 5 block injection aborted."
        )

    def_start = match.start()
    before = source[:def_start]
    after = source[def_start:]

    # Ensure blank line before marker for readability; trailing newline at EOF.
    if before and not before.endswith("\n"):
        before += "\n"
    if not after.endswith("\n"):
        after += "\n"

    return f"{before}{_EVOLVE_BLOCK_START_MARKER}\n{after}{_EVOLVE_BLOCK_END_MARKER}\n"


def _generate_evaluator_file(
    *,
    eval_dir_base: Path,
    baseline_size: int,
    test_file_path: Path,
    train_test_ids: list[str],
    output_dir: Path,
) -> Path:
    """Render `_EVALUATOR_TEMPLATE` to `output_dir/evaluator.py`.

    The generated file is self-contained (Pitfall 1) — it imports score_candidate
    from the parent project at runtime via the sys.path insert at the top.
    Returns the absolute path to the written evaluator file.
    """
    # project_root = the parent of `evolution/` (i.e., the repo root)
    project_root = str(Path(__file__).resolve().parent.parent.parent)

    rendered = _EVALUATOR_TEMPLATE.format(
        project_root=project_root,
        eval_dir_base=str(eval_dir_base),
        baseline_size=int(baseline_size),
        test_file_path=str(test_file_path),
        train_test_ids=list(train_test_ids),
    )

    evaluator_path = output_dir / "evaluator.py"
    evaluator_path.write_text(rendered, encoding="utf-8")
    return evaluator_path


def _build_oe_config(
    evolution_config: "EvolutionConfig",
    iterations: int,
    sandbox_timeout: int,
) -> Config:
    """Build an openevolve Config from EvolutionConfig (D-04 bridge).

    PoC-conservative parameters (Pitfall 4):
        population_size=50, archive_size=20, num_islands=3, parallel_evaluations=1
    """
    oe_config = Config()
    model_cfg = LLMModelConfig(
        name=evolution_config.optimizer_model,
        api_base=evolution_config.api_base or "https://api.openai.com/v1",
        api_key=evolution_config.api_key,
        temperature=0.7,
        max_tokens=4096,
        timeout=sandbox_timeout,
    )
    oe_config.llm.models = [model_cfg]
    oe_config.llm.evaluator_models = [model_cfg]
    oe_config.max_iterations = iterations
    oe_config.database.population_size = _OE_POPULATION_SIZE
    oe_config.database.archive_size = _OE_ARCHIVE_SIZE
    oe_config.database.num_islands = _OE_NUM_ISLANDS
    oe_config.evaluator.timeout = sandbox_timeout
    oe_config.evaluator.cascade_evaluation = False
    oe_config.evaluator.parallel_evaluations = _OE_PARALLEL_EVALUATIONS
    return oe_config


def _extract_metrics(result: Any) -> dict:
    """Best-effort extraction of the metrics dict from an openevolve result.

    openevolve's return type changed across 0.2.x; we accept either a `metrics`
    attribute (dict) or fall back to an empty dict. Never raises.
    """
    try:
        metrics = getattr(result, "metrics", None) or {}
        if isinstance(metrics, dict):
            return dict(metrics)
    except (TypeError, ValueError, AttributeError):
        pass
    return {}


# ── Public entry-point ──────────────────────────────────────────────────────


def evolve(
    target: "CodeTarget",
    config: "EvolutionConfig",
    output_dir: Path,
    iterations: int,
    *,
    sandbox_timeout: int = DEFAULT_SANDBOX_TIMEOUT,
    train_test_ids: Optional[list[str]] = None,
    eval_dir_base: Optional[Path] = None,
) -> EvolutionAdapterResult:
    """Run a darwinian evolution loop on `target` using openevolve.

    Args:
        target: CodeTarget produced by code_target_loader.find_target()
        config: EvolutionConfig with optimizer_model / api_base / api_key
        output_dir: per-run output dir (e.g. output/code/<ts>/); will be created
        iterations: openevolve max iterations
        sandbox_timeout: per-candidate pytest+ruff timeout (default 120s, T-21-DOS)
        train_test_ids: stratified train split from stratify_tests(); the holdout
            split is consumed separately by evolve_code post-evolution
        eval_dir_base: parent dir for per-candidate eval_dir tempdirs; defaults
            to output_dir/"eval"

    Returns:
        EvolutionAdapterResult — narrow type, does NOT expose openevolve internals.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if eval_dir_base is None:
        eval_dir_base = output_dir / "eval"
    eval_dir_base = Path(eval_dir_base)
    eval_dir_base.mkdir(parents=True, exist_ok=True)

    initial_source = _inject_evolve_blocks(target.original_source)
    initial_program_path = output_dir / "initial_program.py"
    initial_program_path.write_text(initial_source, encoding="utf-8")

    evaluator_path = _generate_evaluator_file(
        eval_dir_base=eval_dir_base,
        baseline_size=int(target.baseline_size_bytes),
        test_file_path=Path(target.test_file_path),
        train_test_ids=list(train_test_ids or []),
        output_dir=output_dir,
    )

    oe_config = _build_oe_config(config, iterations, sandbox_timeout)

    oe_internal_dir = output_dir / "openevolve_internal"
    oe_internal_dir.mkdir(parents=True, exist_ok=True)

    result = run_evolution(
        initial_program=str(initial_program_path),
        evaluator=str(evaluator_path),
        config=oe_config,
        iterations=iterations,
        output_dir=str(oe_internal_dir),
        cleanup=False,
    )

    best_code_attr = getattr(result, "best_code", "") or ""
    best_score_attr = getattr(result, "best_score", 0.0) or 0.0

    return EvolutionAdapterResult(
        best_code=str(best_code_attr),
        best_score=float(best_score_attr),
        iterations_run=int(iterations),
        output_dir=oe_internal_dir,
        optimizer_used="openevolve",
        metrics=_extract_metrics(result),
    )


__all__ = [
    "EvolutionAdapterResult",
    "evolve",
    "DEFAULT_SANDBOX_TIMEOUT",
]
