"""Phase 21 Plan 07 — Darwinian code evolution CLI orchestrator.

End-to-end pipeline: pre-flight → CodeTarget → baseline → openevolve evolve →
holdout gate → output/code/<ts>/{component.py, NOTICE.md, metrics.json, diff.txt,
eval_holdout.json}.

V2-CODE-01 primary user entry point.

Usage:
    python -m evolution.code.evolve_code --component tools/ansi_strip.py --dry-run
    python -m evolution.code.evolve_code --component tools/ansi_strip.py \\
        --iterations 20 --model openai/gpt-4o-mini

This module does NOT import openevolve (D-04) — the only openevolve import surface
is evolution.code.code_evolver_adapter, which this module lazy-imports inside
evolve() step 6.
"""

from __future__ import annotations

import difflib
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import click
from rich.console import Console
from rich.panel import Panel

from evolution.code.code_fitness import CodeFitness, score_candidate
from evolution.code.code_target_loader import (
    find_target,
    find_target_tests,
    stratify_tests,
)
from evolution.core.config import EvolutionConfig

console = Console()


# ── D-19 NOTICE.md template ─────────────────────────────────────────────────
# Includes the literal "UNREVIEWED — DO NOT MERGE WITHOUT HUMAN REVIEW" marker.
NOTICE_TEMPLATE = """# NOTICE — LLM-generated code

This code was generated by openevolve via Phase 21 darwinian-code-evolution pipeline.

- Source library: openevolve >=0.2.27 (Apache-2.0)
- Target: hermes-agent/{component_path}
- Generated: {timestamp}
- Status: UNREVIEWED — DO NOT MERGE WITHOUT HUMAN REVIEW
- Fitness: pytest {pytest_passed}/{pytest_total}, size_component {size_component}, ruff_score {ruff_score}, composite {composite}
- Holdout: pytest {holdout_passed}/{holdout_total} (status: {holdout_status})
- Reject reason: {reject_reason}
- Pytest failures (secret-filtered): {failures}

Per project policy (PROJECT.md), evolved artifacts are output-only.
Auto-merge is explicitly out of scope.
"""


# ── Pre-flight (7-step hard gate) ───────────────────────────────────────────


def _run_preflight(
    component: str,
    hermes_repo: Path,
    config: EvolutionConfig,
) -> None:
    """7-step hard pre-flight check (CONTEXT.md §pre-flight).

    Steps 1-5, 7 are blocking (SystemExit(1) on failure).
    Step 6 (.pre-commit-config.yaml) only warns.

    Raises:
        SystemExit(1) on any hard-fail step.
    """
    # 1. import openevolve must be importable via adapter
    try:
        import importlib

        importlib.import_module("evolution.code.code_evolver_adapter")
    except ImportError as e:
        console.print(
            f"[red]✗ Pre-flight 1/7: openevolve not installed.[/red] {e}\n"
            "[yellow]Run: pip install .[code][/yellow]"
        )
        raise SystemExit(1)
    console.print("[green]✓ Pre-flight 1/7: openevolve importable via adapter[/green]")

    # 2. component file exists in hermes-agent
    component_path = hermes_repo / component
    if not component_path.exists():
        console.print(
            f"[red]✗ Pre-flight 2/7: component not found: {component_path}[/red]"
        )
        raise SystemExit(1)
    console.print(f"[green]✓ Pre-flight 2/7: component found at {component_path}[/green]")

    # 3. sibling test file exists & AST-parseable
    import ast as _ast

    component_stem = Path(component).stem
    parts = Path(component).parts
    if len(parts) >= 2:
        test_rel = Path("tests") / Path(*parts[:-1]) / f"test_{component_stem}.py"
    else:
        test_rel = Path("tests") / f"test_{component_stem}.py"
    test_file_path = hermes_repo / test_rel
    if not test_file_path.exists():
        console.print(
            f"[red]✗ Pre-flight 3/7: test file not found: {test_file_path}[/red]"
        )
        raise SystemExit(1)
    try:
        _ast.parse(test_file_path.read_text(encoding="utf-8"))
    except SyntaxError as e:
        console.print(f"[red]✗ Pre-flight 3/7: test file AST parse failed: {e}[/red]")
        raise SystemExit(1)
    console.print(
        f"[green]✓ Pre-flight 3/7: test file ast-parsed at {test_file_path}[/green]"
    )

    # 4. .gitignore contains output/
    gitignore = Path(".gitignore")
    if not gitignore.exists() or "output/" not in gitignore.read_text(encoding="utf-8"):
        console.print(
            "[red]✗ Pre-flight 4/7: .gitignore missing 'output/' entry[/red]"
        )
        raise SystemExit(1)
    console.print("[green]✓ Pre-flight 4/7: .gitignore exempts output/[/green]")

    # 5. LICENSE exists at repo root and is non-empty
    license_path = Path("LICENSE")
    if not license_path.exists() or license_path.stat().st_size == 0:
        console.print(
            "[red]✗ Pre-flight 5/7: LICENSE not found at repo root or empty[/red]"
        )
        raise SystemExit(1)
    console.print("[green]✓ Pre-flight 5/7: LICENSE present and non-empty[/green]")

    # 6. .pre-commit-config.yaml contains openevolve-single-import-surface (warn-only)
    pre_commit = Path(".pre-commit-config.yaml")
    if (
        not pre_commit.exists()
        or "openevolve-single-import-surface" not in pre_commit.read_text(encoding="utf-8")
    ):
        console.print(
            "[yellow]⚠ Pre-flight 6/7: .pre-commit-config.yaml missing "
            "openevolve-single-import-surface hook (D-18 layer-1 not installed). "
            "Continuing (warn-only).[/yellow]"
        )
    else:
        console.print(
            "[green]✓ Pre-flight 6/7: D-18 pre-commit hook installed[/green]"
        )

    # 7. EvolutionConfig already loaded; require api_key non-empty
    if not getattr(config, "api_key", None):
        console.print(
            "[red]✗ Pre-flight 7/7: EvolutionConfig.api_key is empty — "
            "set EVOLUTION_API_KEY or pass --api-base/--model with a configured key[/red]"
        )
        raise SystemExit(1)
    console.print(
        "[green]✓ Pre-flight 7/7: EvolutionConfig resolved (api_key present)[/green]"
    )


# ── D-15 holdout gate ───────────────────────────────────────────────────────


def _check_holdout_gate(fitness: CodeFitness) -> bool:
    """D-15 hard holdout gate: pytest 100% AND size ≥ 0.7 AND ruff ≥ 0.4."""
    return (
        fitness.pytest_total > 0
        and fitness.pytest_passed == fitness.pytest_total
        and fitness.size_component >= 0.7
        and fitness.ruff_score >= 0.4
    )


# ── NOTICE.md writer (Pitfall 7 secret filtering) ───────────────────────────


def _write_notice(
    output_dir: Path,
    target,
    timestamp: str,
    holdout_fitness: CodeFitness,
    reject_reason: str = "",
) -> None:
    """Write NOTICE.md with D-19 UNREVIEWED marker + Pitfall 7 secret filtering."""
    from evolution.core.external_importers import _contains_secret

    def _safe(text) -> str:
        return "[REDACTED]" if _contains_secret(str(text)) else str(text)

    failures_safe = [
        {k: _safe(v) for k, v in (f or {}).items()}
        for f in (holdout_fitness.pytest_failures or [])
    ]
    notice_text = NOTICE_TEMPLATE.format(
        component_path=str(getattr(target, "component_path", "")),
        timestamp=timestamp,
        pytest_passed=holdout_fitness.pytest_passed,
        pytest_total=holdout_fitness.pytest_total,
        size_component=round(holdout_fitness.size_component, 3),
        ruff_score=round(holdout_fitness.ruff_score, 3),
        composite=round(holdout_fitness.composite, 3),
        holdout_passed=holdout_fitness.pytest_passed,
        holdout_total=holdout_fitness.pytest_total,
        holdout_status="pass" if not reject_reason else "fail",
        reject_reason=reject_reason or "none",
        failures=failures_safe,
    )
    (output_dir / "NOTICE.md").write_text(notice_text, encoding="utf-8")


# ── Diff helper ─────────────────────────────────────────────────────────────


def _generate_diff(original: str, evolved: str) -> str:
    """Unified diff between original and evolved source (for diff.txt)."""
    return "".join(
        difflib.unified_diff(
            original.splitlines(keepends=True),
            evolved.splitlines(keepends=True),
            fromfile="original",
            tofile="evolved",
            n=3,
        )
    )


# ── Main business logic ─────────────────────────────────────────────────────


def evolve(
    config: EvolutionConfig,
    component: str,
    dry_run: bool = False,
    allow_fallback: bool = False,
) -> None:
    """Run the full 9-step evolution pipeline.

    Step 5b returns early when ``dry_run`` is True (pre-flight + baseline only).
    """
    hermes_repo = Path(config.hermes_agent_path)

    # Step 1 — pre-flight
    _run_preflight(component, hermes_repo, config)

    # Step 2 — timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Step 3 — CodeTarget
    target = find_target(component, hermes_repo)
    console.print(
        Panel.fit(
            f"component: {target.component_path}\n"
            f"test_file: {target.test_file_path}\n"
            f"baseline_size_bytes: {target.baseline_size_bytes}\n"
            f"hermes_agent_commit: {target.hermes_agent_commit or '(no git)'}",
            title="CodeTarget",
            border_style="cyan",
        )
    )

    # Step 4 — discover & stratify tests
    manifest = find_target_tests(target)
    splits = stratify_tests(manifest, seed=42)
    console.print(
        f"[cyan]Test split[/cyan]: {len(splits['train_ids'])} train / "
        f"{len(splits['holdout_ids'])} holdout"
    )

    # Step 5 — baseline fitness on original source
    eval_dir_base = Path.home() / ".hermes" / "tmp"
    eval_dir_base.mkdir(parents=True, exist_ok=True)
    baseline_fitness = score_candidate(
        target.component_path,
        target.component_path,  # evolved = original (baseline)
        eval_dir_base,
        target.baseline_size_bytes,
        splits["train_ids"],
        test_file_path=target.test_file_path,
    )
    console.print(
        Panel.fit(
            f"pytest: {baseline_fitness.pytest_passed}/{baseline_fitness.pytest_total}\n"
            f"size_component: {round(baseline_fitness.size_component, 3)}\n"
            f"ruff_score: {round(baseline_fitness.ruff_score, 3)}\n"
            f"composite: {round(baseline_fitness.composite, 3)}",
            title="Baseline Fitness",
            border_style="green",
        )
    )

    # Step 5b — dry-run early exit
    if dry_run:
        console.print(
            "[green]DRY RUN -- pre-flight + baseline validated. "
            "Skipping openevolve invocation.[/green]"
        )
        return

    # Step 6 — lazy import adapter (only place that pulls openevolve into the process)
    from evolution.code.code_evolver_adapter import (  # noqa: PLC0415
        EvolutionAdapterResult,
        evolve as _adapter_evolve,
    )

    # Step 7 — run evolution, write best candidate
    output_dir = Path("output") / "code" / timestamp
    output_dir.mkdir(parents=True, exist_ok=True)
    console.print(f"[cyan]Output dir[/cyan]: {output_dir}")

    adapter_result: EvolutionAdapterResult = _adapter_evolve(
        target,
        config,
        output_dir,
        config.iterations,
        train_test_ids=splits["train_ids"],
        eval_dir_base=eval_dir_base,
    )
    best_path = output_dir / Path(target.component_path).name
    best_path.write_text(adapter_result.best_code, encoding="utf-8")

    # Step 8 — holdout score
    holdout_fitness = score_candidate(
        target.component_path,
        best_path,
        eval_dir_base,
        target.baseline_size_bytes,
        splits["holdout_ids"],
        test_file_path=target.test_file_path,
    )

    # Step 9 — D-15 gate
    accepted = _check_holdout_gate(holdout_fitness)
    reject_reason = ""
    if not accepted:
        if holdout_fitness.pytest_passed != holdout_fitness.pytest_total:
            reject_reason = (
                f"holdout pytest {holdout_fitness.pytest_passed}/"
                f"{holdout_fitness.pytest_total} (< 100%)"
            )
        elif holdout_fitness.size_component < 0.7:
            reject_reason = f"size_component {holdout_fitness.size_component:.3f} < 0.7"
        elif holdout_fitness.ruff_score < 0.4:
            reject_reason = f"ruff_score {holdout_fitness.ruff_score:.3f} < 0.4"
        else:
            reject_reason = "unknown D-15 violation"

    diff_text = _generate_diff(target.original_source, adapter_result.best_code)

    metrics = {
        "phase": "21",
        "plan": "07",
        "timestamp": timestamp,
        "component": str(target.component_path),
        "iterations": config.iterations,
        "optimizer_used": adapter_result.optimizer_used,
        "baseline": baseline_fitness.to_dict()
        if hasattr(baseline_fitness, "to_dict")
        else {},
        "holdout": holdout_fitness.to_dict()
        if hasattr(holdout_fitness, "to_dict")
        else {},
        "holdout_gate_passed": accepted,
        "reject_reason": reject_reason,
        "adapter_metrics": adapter_result.metrics,
    }

    if accepted:
        _write_notice(output_dir, target, timestamp, holdout_fitness)
        (output_dir / "metrics.json").write_text(
            json.dumps(metrics, indent=2), encoding="utf-8"
        )
        (output_dir / "diff.txt").write_text(diff_text, encoding="utf-8")
        (output_dir / "eval_holdout.json").write_text(
            json.dumps(
                {
                    "holdout_ids": splits["holdout_ids"],
                    "holdout_fitness": holdout_fitness.to_dict()
                    if hasattr(holdout_fitness, "to_dict")
                    else {},
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        console.print(
            f"[green]✓ ACCEPT — output at {output_dir} (composite "
            f"{round(holdout_fitness.composite, 3)})[/green]"
        )
    else:
        failed_dir = output_dir.parent / f"FAILED_{timestamp}"
        output_dir.rename(failed_dir)
        _write_notice(failed_dir, target, timestamp, holdout_fitness, reject_reason)
        (failed_dir / "metrics.json").write_text(
            json.dumps(metrics, indent=2), encoding="utf-8"
        )
        (failed_dir / "diff.txt").write_text(diff_text, encoding="utf-8")
        console.print(
            f"[red]✗ REJECT (D-15) — {reject_reason} — see {failed_dir}[/red]"
        )
        raise SystemExit(1)


# ── CLI ─────────────────────────────────────────────────────────────────────


@click.command()
@click.option(
    "--component",
    required=True,
    help="hermes-agent component path (e.g. tools/ansi_strip.py)",
)
@click.option("--iterations", default=20, type=int, help="openevolve max iterations")
@click.option(
    "--max-cost",
    "max_cost",
    default=5.0,
    type=float,
    help="Max USD cost budget for the evolve run",
)
@click.option(
    "--hermes-repo",
    default=None,
    type=click.Path(),
    help="Override path to hermes-agent repo",
)
@click.option(
    "--model",
    default=None,
    help="Override LLM model name (e.g. openai/gpt-4o-mini)",
)
@click.option(
    "--api-base",
    default=None,
    help="Override OpenAI-compatible API base URL",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Run pre-flight + baseline only; do NOT call openevolve",
)
@click.option(
    "--allow-fallback",
    is_flag=True,
    default=False,
    help="Allow fallback optimizer if openevolve unavailable (default off)",
)
def main(
    component: str,
    iterations: int,
    max_cost: float,
    hermes_repo: Optional[str],
    model: Optional[str],
    api_base: Optional[str],
    dry_run: bool,
    allow_fallback: bool,
) -> None:
    """Evolve a hermes-agent component using openevolve."""
    config = EvolutionConfig.load(
        iterations=iterations,
        hermes_repo=hermes_repo,
        model=model,
        api_base=api_base,
        max_cost_usd=max_cost,
    )
    evolve(config, component, dry_run=dry_run, allow_fallback=allow_fallback)


if __name__ == "__main__":  # pragma: no cover
    main()
